using System.Linq;
using System.Numerics;
using System.Text;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform; // Far Horizons
    private readonly SharedDockingSystem _dock; // Far Horizons

    // Far Horizons start
    const float MaxDockDistanceSq = SharedDockingSystem.DockRange * SharedDockingSystem.DockRange;
    private static LocId autoDockLabel = "shuttle-console-autodock";
    private static LocId autoUnDockLabel = "shuttle-console-autoundock";
    private bool _docked;
    private bool _dockable;

    private NetEntity? _shuttleNEnt;
    private List<DockingPortState> _docks = [];
    // Far Horizons end

    /// <summary>
    /// Stored by GridID then by docks
    /// </summary>
    public Dictionary<NetEntity, List<DockingPortState>> Docks = new();

    /// <summary>
    /// Store the dock buttons for the side buttons.
    /// </summary>
    private readonly Dictionary<NetEntity, Button> _ourDockButtons = new();

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;
    public event Action<List<NetEntity>>? UndockAllRequest;

    private void InitAutodock() =>
        FHAutoDock.OnPressed += AutoDockRequest; // Far Horizons

    public DockingScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _shuttles = _entManager.System<SharedShuttleSystem>();
        _transform = _entManager.System<SharedTransformSystem>(); // Far Horizons
        _dock = _entManager.System<SharedDockingSystem>(); // Far Horizons

        DockingControl.OnViewDock += OnView;
        DockingControl.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };
        DockingControl.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };

        InitAutodock(); // Far Horizons
    }

    private void OnUndockAllPressed()
    {
        if (UndockAllRequest == null)
            return;

        // Find all docks that belong to the current shuttle and are docked
        var netEntity = _entManager.GetNetEntity(DockingControl.GridEntity!.Value);
        if (!Docks.TryGetValue(netEntity, out var shuttleDocks))
            return;

        var dockedPorts = new List<NetEntity>();

        foreach (var dock in shuttleDocks)
        {
            if (dock.Connected)
            {
                dockedPorts.Add(dock.Entity);
            }
        }

        if (dockedPorts.Count > 0)
        {
            UndockAllRequest.Invoke(dockedPorts);
        }
    }

    private void OnView(NetEntity obj)
    {
        if (_ourDockButtons.TryGetValue(obj, out var viewed))
        {
            viewed.Pressed = true;
        }
    }

    public void UpdateState(EntityUid? shuttle, DockingInterfaceState state)
    {
        Docks = state.Docks;
        DockingControl.DockState = state;
        DockingControl.GridEntity = shuttle;
        BuildDocks(shuttle);

        // Enable the undock all button only if there are docked ports
        var hasDockedPorts = false;
        if (shuttle != null)
        {
            var netEntity = _entManager.GetNetEntity(shuttle.Value);
            if (Docks.TryGetValue(netEntity, out var shuttleDocks))
            {
                hasDockedPorts = shuttleDocks.Any(d => d.Connected);
            }
        }

    }

    private void BuildDocks(EntityUid? shuttle)
    {
        DockingControl.BuildDocks(shuttle);
        var currentDock = DockingControl.ViewedDock;
        // DockedWith.DisposeAllChildren();
        DockPorts.DisposeAllChildren();
        _ourDockButtons.Clear();
        SetAutodockState(shuttle); // Far Horizons

        if (shuttle == null)
        {
            DockingControl.SetViewedDock(null);
            return;
        }

        var shuttleNent = _entManager.GetNetEntity(shuttle.Value);

        if (!Docks.TryGetValue(shuttleNent, out var shuttleDocks) || shuttleDocks.Count <= 0)
            return;

        var dockText = new StringBuilder();
        var buttonGroup = new ButtonGroup();
        var idx = 0;
        var selected = false;
        DockingPortState? firstState = null; // Frontier

        // Build the dock buttons for our docks.
        foreach (var dock in shuttleDocks.OrderBy(x => x.LabelName ?? x.Name)) // Frontier: order by name
        {
            if (idx == 0) // Frontier: get first element
                firstState = dock; // Frontier: get first element

            idx++;
            dockText.Clear();
            dockText.Append(dock.LabelName ?? dock.Name); // Frontier: prefer label name

            var button = new Button()
            {
                Text = dockText.ToString(),
                ToggleMode = true,
                Group = buttonGroup,
                Margin = new Thickness(0f, 3f),
            };

            button.OnMouseEntered += args =>
            {
                DockingControl.HighlightedDock = dock.Entity;
            };

            button.OnMouseExited += args =>
            {
                DockingControl.HighlightedDock = null;
            };

            button.Label.Margin = new Thickness(3f);

            if (currentDock == dock.Entity)
            {
                selected = true;
                button.Pressed = true;
            }

            button.OnPressed += args =>
            {
                OnDockPress(dock);
            };

            _ourDockButtons[dock.Entity] = button;
            DockPorts.AddChild(button);
        }

        // Button group needs one selected so just show the first one.
        if (!selected)
        {
            // Frontier: press first button in alphabetical order
            // var buttonOne = shuttleDocks[0];
            // OnDockPress(buttonOne);
            OnDockPress(firstState!);
            // End Frontier
        }

        var shuttleContainers = new Dictionary<NetEntity, DockObject>();

        foreach (var dock in shuttleDocks.OrderBy(x => x.GridDockedWith))
        {
            if (dock.GridDockedWith == null)
                continue;

            DockObject? dockContainer;

            if (!shuttleContainers.TryGetValue(dock.GridDockedWith.Value, out dockContainer))
            {
                dockContainer = new DockObject();
                shuttleContainers[dock.GridDockedWith.Value] = dockContainer;
                var dockGrid = _entManager.GetEntity(dock.GridDockedWith);
                string? iffLabel = null;

                if (_entManager.EntityExists(dockGrid))
                {
                    iffLabel = _shuttles.GetIFFLabel(dockGrid.Value);
                }

                iffLabel ??= Loc.GetString("shuttle-console-unknown");
                dockContainer.SetName(iffLabel);
                // DockedWith.AddChild(dockContainer);
            }

            dockContainer.AddDock(dock, DockingControl);
        }
    }

    private void OnDockPress(DockingPortState state)
    {
        DockingControl.SetViewedDock(state);
    }

    // Far Horizons start
    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_shuttleNEnt == null)
            return;

        SetDocked();
        SetDockable();
        UpdateAutodockButton();
    }

    private void SetAutodockState(EntityUid? shuttle)
    {
        if (shuttle == null)
            return;

        _shuttleNEnt = _entManager.GetNetEntity(shuttle.Value);
        if (_shuttleNEnt == null || !Docks.TryGetValue(_shuttleNEnt.Value, out var shuttleDocks) || shuttleDocks.Count <= 0)
            return;
        _docks = shuttleDocks;
    }

    private void SetDocked() =>
        _docked = _docks.Any(dock => dock.Connected);

    private void SetDockable()
    {
        _dockable = false;

        if (_docked)
        {
            _dockable = true;
            return;
        }

        foreach (var dock in _docks)
        {
            var dockCoords = _entManager.GetCoordinates(dock.Coordinates);
            var dockMapCoords = _transform.ToMapCoordinates(dockCoords);
            var dockRot = _transform.GetWorldRotation(dockCoords.EntityId) + dock.Angle;

            foreach (var otherDock in Docks.Where(kv => kv.Key != _shuttleNEnt).SelectMany(kv => kv.Value))
            {
                var otherDockCoords = _entManager.GetCoordinates(otherDock.Coordinates);
                var otherDockMapCoords = _transform.ToMapCoordinates(otherDockCoords);

                var distanceSq = (dockMapCoords.Position - otherDockMapCoords.Position).LengthSquared();

                if (distanceSq > MaxDockDistanceSq)
                    continue;

                var otherDockRot = _transform.GetWorldRotation(otherDockCoords.EntityId) + otherDock.Angle;
                if (!_dock.InAlignment(dockMapCoords, dockRot, otherDockMapCoords, otherDockRot)) continue;

                _dockable = true;
                return;
            }
        }
    }

    private void UpdateAutodockButton()
    {
        FHAutoDock.Text = Loc.GetString(_docked ? autoUnDockLabel : autoDockLabel);
        FHAutoDock.Disabled = !_dockable;
    }

    private void AutoDockRequest(BaseButton.ButtonEventArgs args)
    {
        if (_shuttleNEnt == null ||
            !_dockable)
            return;

        if (_docked)
        {
            UndockAll();
            return;
        }

        DockAll();
    }

    private void UndockAll()
    {
        foreach (var dock in _docks.Where(dock => dock.Connected))
            UndockRequest?.Invoke(dock.Entity);
    }

    private void DockAll()
    {
        foreach (var dock in _docks)
        {
            var dockCoords = _entManager.GetCoordinates(dock.Coordinates);
            var dockMapCoords = _transform.ToMapCoordinates(dockCoords);
            var dockRot = _transform.GetWorldRotation(dockCoords.EntityId) + dock.Angle;

            foreach (var otherDock in Docks.Where(kv => kv.Key != _shuttleNEnt).SelectMany(kv => kv.Value))
            {
                var otherDockCoords = _entManager.GetCoordinates(otherDock.Coordinates);
                var otherDockMapCoords = _transform.ToMapCoordinates(otherDockCoords);

                var distanceSq = (dockMapCoords.Position - otherDockMapCoords.Position).LengthSquared();

                if (distanceSq > MaxDockDistanceSq)
                    continue;

                var otherDockRot = _transform.GetWorldRotation(otherDockCoords.EntityId) + otherDock.Angle;
                if (!_dock.InAlignment(dockMapCoords, dockRot, otherDockMapCoords, otherDockRot))
                    continue;

                DockRequest?.Invoke(dock.Entity, otherDock.Entity);
            }
        }
    }
    // Far Horizons end
}
