using Content.Shared._FS.LiveStream;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._FS.LiveStream;

[GenerateTypedNameReferences]
public sealed partial class LiveStreamUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public event Action<LiveStreamMessageType, string>? OnSendMessage;

    private NetEntity? _watchedCam;

    public LiveStreamUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartStreamBtn.OnPressed += _ =>
        {
            OnSendMessage?.Invoke(LiveStreamMessageType.StartStream, StreamTitleInput.Text);
            StreamTitleInput.Clear();
        };

        StopStreamBtn.OnPressed += _ => OnSendMessage?.Invoke(LiveStreamMessageType.StopStream, string.Empty);

        StreamerChatSendBtn.OnPressed += _ => SendChat(StreamerChatInput);
        StreamerChatInput.OnTextEntered += _ => SendChat(StreamerChatInput);

        ViewerSendBtn.OnPressed += _ => SendChat(ViewerChatInput);
        ViewerChatInput.OnTextEntered += _ => SendChat(ViewerChatInput);

        BackToListBtn.OnPressed += _ => OnSendMessage?.Invoke(LiveStreamMessageType.StopWatching, string.Empty);

        ViewerDonateBtn.OnToggled += args => DonatePanel.Visible = args.Pressed;

        DonateSubmitBtn.OnPressed += _ =>
        {
            if (!int.TryParse(DonateAmountInput.Text, out var amount) || amount <= 0)
                return;

            OnSendMessage?.Invoke(LiveStreamMessageType.SendDonate, $"{amount}|{DonateMessageInput.Text}");
            DonateAmountInput.Clear();
            DonateMessageInput.Clear();
        };
    }

    private void SendChat(LineEdit input)
    {
        if (string.IsNullOrWhiteSpace(input.Text))
            return;

        OnSendMessage?.Invoke(LiveStreamMessageType.SendChat, input.Text);
        input.Clear();
    }

    public void UpdateState(LiveStreamCartridgeUiState state)
    {
        ListScreen.Visible = !state.IsStreaming && state.WatchedCamNetEntity is null;
        StreamerScreen.Visible = state.IsStreaming;
        ViewerScreen.Visible = !state.IsStreaming && state.WatchedCamNetEntity is not null;

        StartStreamBtn.Disabled = !state.HasCamera;
        StreamCountLabel.Text = Loc.GetString("live-stream-count-label", ("count", state.ActiveStreams.Count), ("max", 5));

        RebuildStreamList(state.ActiveStreams);

        if (state.IsStreaming)
        {
            StreamerLiveLabel.Text = Loc.GetString("live-stream-live-label", ("title", state.StreamTitle));
            StreamerViewerLabel.Text = Loc.GetString("live-stream-viewer-count-label", ("count", state.ViewerCount));
            RenderChat(StreamerChatContainer, state.ChatMessages);
        }

        if (state.WatchedCamNetEntity is not null)
        {
            ViewerStreamerLabel.Text = Loc.GetString("live-stream-watching-label", ("name", state.WatchedStreamerName));
            ViewerLiveLabel.Text = Loc.GetString("live-stream-viewer-count-label", ("count", 0));
            RenderChat(ViewerChatContainer, state.ChatMessages);
        }

        UpdateCameraView(state.WatchedCamNetEntity);
    }

    private void UpdateCameraView(NetEntity? watchedCamNetEntity)
    {
        if (watchedCamNetEntity == _watchedCam)
            return;

        _watchedCam = watchedCamNetEntity;

        IEye? eye = null;
        if (watchedCamNetEntity is not null)
        {
            var cam = _entManager.GetEntity(watchedCamNetEntity);
            if (cam is { Valid: true } && _entManager.TryGetComponent<EyeComponent>(cam, out var eyeComp))
                eye = eyeComp.Eye;
        }

        CameraView.Eye = eye;
    }

    private void RebuildStreamList(List<LiveStreamInfo> streams)
    {
        StreamListContainer.RemoveAllChildren();

        foreach (var stream in streams)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2, 0, 2),
            };

            row.AddChild(new Label
            {
                Text = Loc.GetString("live-stream-list-entry", ("title", stream.Title), ("streamer", stream.StreamerName), ("count", stream.ViewerCount)),
                HorizontalExpand = true,
                ClipText = true,
            });

            var watchButton = new Button { Text = Loc.GetString("live-stream-watch-button") };
            var netEntity = stream.CamNetEntity;
            watchButton.OnPressed += _ => OnSendMessage?.Invoke(LiveStreamMessageType.WatchStream, netEntity.ToString());

            row.AddChild(watchButton);
            StreamListContainer.AddChild(row);
        }
    }

    private static void RenderChat(BoxContainer container, List<LiveStreamChatMessage> messages)
    {
        container.RemoveAllChildren();

        foreach (var message in messages)
        {
            var color = message.IsSystem ? "#E0A030" : "#8FD0FF";
            var sender = FormattedMessage.EscapeText(message.Sender);
            var text = FormattedMessage.EscapeText(message.Text);

            var label = new RichTextLabel();
            label.SetMessage($"[color={color}]{sender}:[/color] {text}");
            container.AddChild(label);
        }
    }
}
