using System.Threading;
using Content.Shared._FS.LiveStream;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Graphics;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._FS.LiveStream;

[GenerateTypedNameReferences]
public sealed partial class LiveStreamUiFragment : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private readonly SharedTransformSystem _transform;

    public event Action<LiveStreamMessageType, string>? OnSendMessage;

    private NetEntity? _watchedCam;
    private CancellationTokenSource? _eyeRetryCts;

    // Chat is append-only per view; track how much of the log we've already rendered so a new
    // message doesn't force a full RemoveAllChildren+rebuild of up to MaxChatMessages labels.
    private int _streamerChatRendered;
    private int _viewerChatRendered;

    public LiveStreamUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _transform = _entManager.System<SharedTransformSystem>();

        // ScalingViewport defaults ViewportSize to (0, 0), which makes RegenerateViewport() create a
        // zero-sized render target - the camera feed silently renders nothing instead of erroring.
        CameraView.ViewportSize = new Vector2i(260, 190);

        StartStreamBtn.OnPressed += _ =>
        {
            OnSendMessage?.Invoke(LiveStreamMessageType.StartStream, StreamTitleInput.Text);
            StreamTitleInput.Clear();
        };

        StopStreamBtn.OnPressed += _ => OnSendMessage?.Invoke(LiveStreamMessageType.StopStream, string.Empty);

        StreamerChatSendBtn.OnPressed += _ => SendChat(StreamerChatInput);
        StreamerChatInput.OnTextEntered += _ => SendChat(StreamerChatInput);

        ViewerSendBtn.OnPressed += _ => SendChat(ViewerChatInput);
        ViewerChatInput.OnTextEntered += _ => SendChat(ViewerChatInput);

        BackToListBtn.OnPressed += _ => OnSendMessage?.Invoke(LiveStreamMessageType.StopWatching, string.Empty);

        ViewerDonateBtn.OnToggled += args => DonatePanel.Visible = args.Pressed;

        DonateSubmitBtn.OnPressed += _ =>
        {
            if (!int.TryParse(DonateAmountInput.Text, out var amount) || amount <= 0)
                return;

            OnSendMessage?.Invoke(LiveStreamMessageType.SendDonate, $"{amount}|{DonateMessageInput.Text}");
            DonateAmountInput.Clear();
            DonateMessageInput.Clear();
        };
    }

    private void SendChat(LineEdit input)
    {
        if (string.IsNullOrWhiteSpace(input.Text))
            return;

        OnSendMessage?.Invoke(LiveStreamMessageType.SendChat, input.Text);
        input.Clear();
    }

    public void UpdateState(LiveStreamCartridgeUiState state)
    {
        ListScreen.Visible = !state.IsStreaming && state.WatchedCamNetEntity is null;
        StreamerScreen.Visible = state.IsStreaming;
        ViewerScreen.Visible = !state.IsStreaming && state.WatchedCamNetEntity is not null;

        StartStreamRow.Visible = state.CanBroadcast;
        StartStreamBtn.Disabled = !state.HasCamera;
        StreamCountLabel.Text = Loc.GetString("live-stream-count-label", ("count", state.ActiveStreams.Count), ("max", 5));

        RebuildStreamList(state.ActiveStreams);

        if (state.IsStreaming)
        {
            StreamerLiveLabel.Text = Loc.GetString("live-stream-live-label", ("title", state.StreamTitle));
            StreamerViewerLabel.Text = Loc.GetString("live-stream-viewer-count-label", ("count", state.ViewerCount));
            RenderChat(StreamerChatContainer, state.ChatMessages, ref _streamerChatRendered);
            RebuildDonators(StreamerDonatorsList, state.TopDonators);
        }
        else if (_streamerChatRendered != 0)
        {
            StreamerChatContainer.RemoveAllChildren();
            _streamerChatRendered = 0;
        }

        if (state.WatchedCamNetEntity is not null)
        {
            ViewerStreamerLabel.Text = Loc.GetString("live-stream-watching-label", ("name", state.WatchedStreamerName));
            ViewerLiveLabel.Text = Loc.GetString("live-stream-viewer-count-label", ("count", 0));
            RenderChat(ViewerChatContainer, state.ChatMessages, ref _viewerChatRendered);
            RebuildDonators(ViewerDonatorsList, state.TopDonators);
        }
        else if (_viewerChatRendered != 0)
        {
            ViewerChatContainer.RemoveAllChildren();
            _viewerChatRendered = 0;
        }

        UpdateCameraView(state.WatchedCamNetEntity);
    }

    /// <summary>
    /// The watched cam's entity (and its EyeComponent) may not have arrived over PVS yet the instant
    /// the server tells us to watch it - retry for a bit instead of giving up after one failed lookup.
    /// </summary>
    private void UpdateCameraView(NetEntity? watchedCamNetEntity)
    {
        if (watchedCamNetEntity == _watchedCam)
            return;

        _watchedCam = watchedCamNetEntity;
        _eyeRetryCts?.Cancel();
        CameraView.Eye = null;

        if (watchedCamNetEntity is not { } netEntity)
            return;

        _eyeRetryCts = new CancellationTokenSource();
        TryResolveCameraEye(netEntity, retriesLeft: 8, _eyeRetryCts.Token);
    }

    /// <summary>
    /// The engine only tracks the eye's position automatically (map-absolute, so it already follows
    /// whatever grid the cam is on), never its rotation - the feed would otherwise stay "map north up"
    /// even while the cam's grid (e.g. a flying shuttle) turns under it. Counter-rotate every frame so
    /// the feed stays upright relative to the grid instead.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (CameraView.Eye is not { } eye || _watchedCam is not { } netEntity)
            return;

        var cam = _entManager.GetEntity(netEntity);
        if (cam is not { Valid: true }
            || !_entManager.TryGetComponent<TransformComponent>(cam, out var xform)
            || xform.GridUid is not { } grid)
        {
            return;
        }

        eye.Rotation = _transform.GetWorldRotation(grid);
    }

    private void TryResolveCameraEye(NetEntity netEntity, int retriesLeft, CancellationToken token)
    {
        if (token.IsCancellationRequested || _watchedCam != netEntity)
            return;

        var cam = _entManager.GetEntity(netEntity);
        if (cam is { Valid: true } && _entManager.TryGetComponent<EyeComponent>(cam, out var eyeComp))
        {
            CameraView.Eye = eyeComp.Eye;
            return;
        }

        if (retriesLeft <= 0)
            return;

        Robust.Shared.Timing.Timer.Spawn(250, () => TryResolveCameraEye(netEntity, retriesLeft - 1, token), token);
    }

    private static void RebuildDonators(BoxContainer container, List<LiveStreamDonatorInfo> donators)
    {
        container.RemoveAllChildren();

        if (donators.Count == 0)
        {
            container.AddChild(new Label { Text = Loc.GetString("live-stream-top-donators-empty") });
            return;
        }

        foreach (var donator in donators)
        {
            container.AddChild(new Label
            {
                Text = Loc.GetString("live-stream-top-donators-entry", ("name", donator.Name), ("amount", donator.Amount)),
                ClipText = true,
            });
        }
    }

    private void RebuildStreamList(List<LiveStreamInfo> streams)
    {
        StreamListContainer.RemoveAllChildren();

        foreach (var stream in streams)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2, 0, 2),
            };

            row.AddChild(new Label
            {
                Text = Loc.GetString("live-stream-list-entry", ("title", stream.Title), ("streamer", stream.StreamerName), ("count", stream.ViewerCount)),
                HorizontalExpand = true,
                ClipText = true,
            });

            var watchButton = new Button { Text = Loc.GetString("live-stream-watch-button") };
            var netEntity = stream.CamNetEntity;
            watchButton.OnPressed += _ => OnSendMessage?.Invoke(LiveStreamMessageType.WatchStream, netEntity.ToString());

            row.AddChild(watchButton);
            StreamListContainer.AddChild(row);
        }
    }

    private static void RenderChat(BoxContainer container, List<LiveStreamChatMessage> messages, ref int rendered)
    {
        // Log got shorter (switched stream, or the server-side ring buffer trimmed it) - only then
        // pay for a full rebuild; the common case (one more message appended) just adds one label.
        if (messages.Count < rendered)
        {
            container.RemoveAllChildren();
            rendered = 0;
        }

        for (var i = rendered; i < messages.Count; i++)
            container.AddChild(BuildChatLabel(messages[i]));

        rendered = messages.Count;
    }

    private static RichTextLabel BuildChatLabel(LiveStreamChatMessage message)
    {
        var color = message.IsSystem ? "#E0A030" : "#8FD0FF";
        var sender = FormattedMessage.EscapeText(message.Sender);
        var text = FormattedMessage.EscapeText(message.Text);

        var label = new RichTextLabel();
        label.SetMessage(FormattedMessage.FromMarkupPermissive($"[color={color}]{sender}:[/color] {text}"));
        return label;
    }
}
