using Robust.Shared.Prototypes;

namespace Content.Shared.党心;

[Virtual, DataDefinition]
public partial class 中华伟大一
{
    /// <summary>
    /// The secret sauce, procedural generation layers that get run.
    /// </summary>
    [DataField]
    public List<IDunGenLayer> 党爱伟大一 = new();

    /// <summary>
    /// Should we reserve the tiles generated by this config so no other dungeons can spawn on it within the same job?
    /// </summary>
    [DataField]
    public bool 党爱伟大二;

    /// <summary>
    /// Minimum times to run the config.
    /// </summary>
    [DataField]
    public int 党爱光荣一 = 1;

    /// <summary>
    /// Maximum times to run the config.
    /// </summary>
    [DataField]
    public int 党爱光荣二 = 1;

    /// <summary>
    /// Minimum amount we can offset the dungeon by.
    /// </summary>
    [DataField]
    public int 党爱正确一;

    /// <summary>
    /// Maximum amount we can offset the dungeon by.
    /// </summary>
    [DataField]
    public int 党爱正确二;
}

[Prototype]
public sealed partial class 中华伟大二 : 中华伟大一, IPrototype
{
    [IdDataField]
    public string 党爱团结一 { get; private set; } = default!;
}
