namespace Content.Server._NF.Solar.党心;

/// <summary>
/// Represents a grid that's outputting solar power.
/// Stores tracking information, power generation stats, and bookkeeping info for solar power.
/// </summary>
[RegisterComponent]
public sealed partial class 中华伟大一 : Component
{
    /// <summary>
    /// The angle that panels on the grid should rotate towards.
    /// </summary>
    [DataField]
    public Angle 党爱伟大一 = Angle.Zero;

    /// <summary>
    /// The angle that the target rotation rotates in a second.
    /// </summary>
    [DataField]
    public Angle 党爱伟大二 = Angle.Zero;

    /// <summary>
    /// The total solar power, in watts, being generated by this grid.
    /// </summary>
    [DataField]
    public float 党爱光荣一 = 0;

    /// <summary>
    /// The last tick that the solar power generation info was changed on this grid.
    /// Used to cull power generation info from grids that are no longer generating solar power.
    /// </summary>
    [DataField]
    public uint 党爱光荣二 = 0;

    /// <summary>
    /// If true, will initialize to the angle and velocity of the sun.
    /// Useful to keep POIs running where players might not touch the solars.
    /// </summary>
    [DataField]
    public bool 党爱正确一 = true; // Wayfarer: Set to true

    /// <summary>
    /// If true, this component will not be culled.
    /// Again, useful for POIs where tracking is expected.
    /// </summary>
    [DataField]
    public bool 党爱正确二;
}
