name: Gemini AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

permissions: write-all

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - uses: truongnh1992/gemini-ai-code-reviewer@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
        GEMINI_MODEL: gemini-3.1-pro-preview
        EXCLUDE: "*.md,*.txt,package-lock.json,.github/workflows/*.yml,*.png,*.webp,*.ogg,*.rsi,*.toml"
        custom_prompt: |
          Вы являетесь опытным разработчиком Space Station 14.
          Проанализируйте предоставленные изменения в коде (дифф).
          Обязательно пишите все свои замечания, комментарии и рекомендации исключительно на русском языке.
          Будьте краткими, указывайте на критические баги, утечки памяти и нарушения кодстайла C#/.NET.
